### ISSUE TITLE
struct.error: unpack requires a bytes object of length 4

### ISSUE THREAD

**Issue by dhilipsiva** [appknox/androguard#1]
In this line: 

https://github.com/appknox/androguard/blob/64602fa76977e4eab77e5c6639d97bb6db1e18d0/androguard/core/bytecodes/dvm.py#L4389

```
WARNING: error while decoding instruction ...
[2015-12-03 06:24:11,412: WARNING/Worker-1] error while decoding instruction ...
[2015-12-03 06:24:11,426: WARNING/Worker-1] Traceback (most recent call last):
[2015-12-03 06:24:11,426: WARNING/Worker-1] File "/Users/dhilipsiva/Projects/appknox/androguard/androguard/core/bytecodes/dvm.py", line 6395, in get_instructions
    obj = get_instruction_payload(op_value, insn[idx:])
[2015-12-03 06:24:11,426: WARNING/Worker-1] File "/Users/dhilipsiva/Projects/appknox/androguard/androguard/core/bytecodes/dvm.py", line 6353, in get_instruction_payload
    return DALVIK_OPCODES_PAYLOAD[op_value][0](buff)
[2015-12-03 06:24:11,426: WARNING/Worker-1] File "/Users/dhilipsiva/Projects/appknox/androguard/androguard/core/bytecodes/dvm.py", line 4389, in __init__
    self.targets.append(unpack('=l', buff[idx:idx + 4])[0])
[2015-12-03 06:24:11,426: WARNING/Worker-1] struct.error: unpack requires a bytes object of length 4
```

**Comment by dhilipsiva** [comment]
@subho007 Can you do something about this?

**Comment by subho007** [comment]
do you want me to do something about this @dhilipsiva in this week ?

**Comment by dhilipsiva** [comment]
No Subho - Ignore this.
